### ISSUE TITLE
`docker-compose run init` error `ModuleNotFoundError: No module named 'itchat'`

### ISSUE THREAD

**Issue by guyskk** [dongweiming/wechat-admin#19]
```
$ docker-compose run init
Creating network "wechatadmin_bridge" with driver "bridge"
Creating volume "wechatadmin_mysql-data" with local driver
Creating wechatadmin_mysql_1 ... 
Creating wechatadmin_redis_1 ... 
Creating wechatadmin_mysql_1
Creating wechatadmin_mysql_1 ... done
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 351, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/web/manager.py", line 4, in <module>
    from views.api import json_api as app
  File "/web/views/__init__.py", line 1, in <module>
    from .api import json_api  # noqa
  File "/web/views/api.py", line 7, in <module>
    from itchat.signals import scan_qr_code, confirm_login, logged_in
ModuleNotFoundError: No module named 'itchat'
```
貌似是 requirements.txt 中 `-e` 参数的问题，我把它去掉，重新build就正常了
```
-e git+https://github.com/dongweiming/wxpy@signals#egg=wxpy
-e git+https://github.com/dongweiming/ItChat@signals#egg=itchat
```

**Comment by dongweiming** [comment]
@guyskk 之前可能是有这个问题。不过后来我修了， https://github.com/dongweiming/wxpy/commit/d0cd7b7bc30e125c9123a018dae2d0fb0755bf4e。所以感觉是之前build过，之后都是用的缓存。你可以把旧的容器和镜像都删掉重试：

```bash
docker stop $(docker ps -a | grep "wechatadmin" | awk '{print $1}')
docker rm $(docker ps -a | grep "wechatadmin" | awk '{print $1}')
docker rmi $(docker images | grep "wechatadmin" | awk '{print $1}') 
```
