### ISSUE TITLE
安装 ItChat 时缺少依赖

### ISSUE THREAD

**Issue by z333d** [dongweiming/wechat-admin#2]
在虚拟环境中安装项目依赖： pip install -r requirements.txt 出现以下依赖错误：
```
Updating /Users/fakeuser/.pyenv/versions/3.5.0/envs/wechat-admin/src/itchat clone (to signals)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/fakeuser/.pyenv/versions/3.5.0/envs/wechat-admin/src/itchat/setup.py", line 9, in <module>
        import itchat
      File "/Users/fakeuser/.pyenv/versions/3.5.0/envs/wechat-admin/src/itchat/itchat/__init__.py", line 2, in <module>
        from .core import Core
      File "/Users/fakeuser/.pyenv/versions/3.5.0/envs/wechat-admin/src/itchat/itchat/core.py", line 3, in <module>
        import requests
    ImportError: No module named 'requests'
```

在 requirements.txt  应该还需要添加 ItChat 的一些依赖：requests, pyqrcode, blinker

**Comment by dongweiming** [comment]
已经修了 重新安装就好了
