### ISSUE TITLE
启动服务后，访问web，服务报SSLError 

### ISSUE THREAD

**Issue by xxl-xxl** [dongweiming/wechat-admin#29]
[2017-08-03 10:46:51 +0800] [30997] [INFO] Using worker: sync
[2017-08-03 10:46:51 +0800] [31000] [INFO] Booting worker with pid: 31000
[2017-08-03 10:46:51 +0800] [31001] [INFO] Booting worker with pid: 31001
[2017-08-03 10:46:51 +0800] [31002] [INFO] Booting worker with pid: 31002
[2017-08-03 10:46:51 +0800] [31003] [INFO] Booting worker with pid: 31003
[2017-08-03 10:46:51 +0800] [31004] [INFO] Booting worker with pid: 31004
[2017-08-03 10:46:51 +0800] [31005] [INFO] Booting worker with pid: 31005
Traceback (most recent call last):
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/local/python/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/local/python/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/wechat-admin/venv/src/itchat/itchat/utils.py", line 128, in test_connect
    r = requests.get(config.BASE_URL)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

You can't get access to internet or wechat domain, so exit.

**Comment by xxl-xxl** [comment]
发https 请求时，是不是需要忽略证书的验证？

**Comment by dongweiming** [comment]
善用Google
