### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#3]
```bash
[root@localhost wechat-admin]# npm run build

> wechat-vue-admin@1.0.0 build /vagrant/wechat-admin
> node build/build.js

⠼ building for production...
Starting to optimize CSS...
Processing static/css/app.css...
Processed static/css/app.css, before: 310154, after: 307856, ratio: 99.26%
Hash: ed2cc32e226f95fff7f6
Version: webpack 2.7.0
Time: 67553ms
                                 Asset       Size  Chunks                    Chunk Names
                      static/js/app.js     109 kB       1  [emitted]         app
    static/img/fontawesome-webfont.svg     444 kB          [emitted]  [big]  
  static/fonts/fontawesome-webfont.ttf     166 kB          [emitted]         
static/fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]         
 static/fonts/fontawesome-webfont.woff      98 kB          [emitted]         
        static/fonts/element-icons.ttf    13.2 kB          [emitted]         
                   static/js/vendor.js     681 kB       0  [emitted]  [big]  vendor
  static/fonts/fontawesome-webfont.eot     166 kB          [emitted]         
                 static/js/manifest.js    1.43 kB       2  [emitted]         manifest
                    static/css/app.css     308 kB       1  [emitted]  [big]  app
               static/js/vendor.js.map    4.37 MB       0  [emitted]         vendor
                  static/js/app.js.map     187 kB       1  [emitted]         app
                static/css/app.css.map     343 kB       1  [emitted]         app
             static/js/manifest.js.map    14.3 kB       2  [emitted]         manifest
                  templates/index.html  349 bytes          [emitted]         

ERROR in ./src/plugins/emoji/src/api/emoji.js
Module build failed: SyntaxError: Unexpected token (4:16)

  2 | let emojiData = {}
  3 | Object.values(data).forEach(item => {
> 4 |   emojiData = { ...emojiData, ...item }
    |                 ^
  5 | })
  6 | 
  7 | /**

 @ ./src/main.js 14:0-57

ERROR in static/js/app.js from UglifyJs
Unexpected token operator «=», expected punc «,» [./src/plugins/wechat.js:3,26][static/js/app.js:63,34]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.
```

这是不是跟nodejs的版本有关呢？小白，望README写的更清楚些。目前想运行起来看效果。

**Comment by dongweiming** [comment]
缺了.babelrc文件。再试试

**Comment by Lzlor** [comment]
(env) [root@vod01 wechat-admin]# /usr/local/n/versions/node/8.2.1/bin/node run build
module.js:487
    throw err;
    ^

Error: Cannot find module '/opt/wechat-admin/run'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
(env) [root@vod01 wechat-admin]# ls run
ls: 无法访问run: 没有那个文件或目录

node run build错误，跟node版本有关吗？望解答

**Comment by dongweiming** [comment]
npm run build
