### ISSUE TITLE
出现这个错误是gunicorn版本的问题嘛,我按照requirement安装的呀,求教

### ISSUE THREAD

**Issue by Fartown** [dongweiming/wechat-admin#37]
[2017-08-22 10:24:45 +0800] [566] [INFO] Starting gunicorn 19.7.1
Traceback (most recent call last):
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/sock.py", line 44, in set_options
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
OSError: [Errno 92] Protocol not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 198, in run
    self.start()
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 157, in start
    self.LISTENERS = sock.create_sockets(self.cfg, self.log, fds)
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/sock.py", line 180, in create_sockets
    sock = sock_type(addr, conf, log)
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/sock.py", line 32, in __init__
    self.sock = self.set_options(sock, bound=bound)
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/sock.py", line 89, in set_options
    return super(TCPSocket, self).set_options(sock, bound=bound)
  File "/home/wechat-admin/venv/lib/python3.5/site-packages/gunicorn/sock.py", line 46, in set_options
    if err[0] not in (errno.ENOPROTOOPT, errno.EINVAL):
TypeError: 'OSError' object is not subscriptable

**Comment by dongweiming** [comment]
你可以直接去对应项目的repo里面翻： 比如这个 https://github.com/benoitc/gunicorn/issues/1501

**Comment by fengxianxp** [comment]
楼主，问题解决了么，你也是弄Jumpserver吧，我也碰到一样的问题，日志为空，不知道怎么定位问题

**Comment by fengxianxp** [comment]
就这么神奇，用jumpserver官网提供的依赖列表里面的版本gunicorn（19.7.1），就是不好用，改成gunicorn（19.4.5）就好了
