### ISSUE TITLE
启动服务后后台报错

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#4]
您好，更新了你的库之后，重新执行了：

```bash
npm run build
```

没有出现编译错误了，同时，把`dev`和`prod`两个文件里的`API_URL`改为了我虚拟机的地址。再执行：

```bash
venv/bin/gunicorn app:app --bind 192.168.33.10:8100 -w 4 -t 0
```

解决了地址问题。但是，依旧出现不了二维码，后台报：

```bash
[2017-07-18 10:11:01 +0800] [27177] [INFO] Listening at: http://192.168.33.10:8100 (27177)
[2017-07-18 10:11:01 +0800] [27177] [INFO] Using worker: sync
[2017-07-18 10:11:01 +0800] [27180] [INFO] Booting worker with pid: 27180
[2017-07-18 10:11:01 +0800] [27181] [INFO] Booting worker with pid: 27181
[2017-07-18 10:11:01 +0800] [27182] [INFO] Booting worker with pid: 27182
[2017-07-18 10:11:01 +0800] [27183] [INFO] Booting worker with pid: 27183
Getting uuid of QR code.
Downloading QR code.
[2017-07-18 10:11:10 +0800] [27180] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
    six.reraise(*sys.exc_info())
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/wechat-admin/views/api.py", line 83, in login
    user = get_logged_in_user(current_bot)
  File "/vagrant/wechat-admin/libs/wx.py", line 57, in get_logged_in_user
    user_ = bot.self
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/vagrant/wechat-admin/libs/globals.py", line 8, in _find_bot
    top = get_bot()
  File "/vagrant/wechat-admin/libs/wx.py", line 36, in get_bot
    here, '../static/img/qr_code.png'))
  File "/vagrant/wechat-admin/venv/src/wxpy/wxpy/api/bot.py", line 85, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/components/register.py", line 31, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/components/login.py", line 46, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/components/login.py", line 122, in get_QR
    utils.print_qr(picDir)
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/python3.6.2/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/python3.6.2/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/python3.6.2/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'
```

**Comment by aqiansunboy** [comment]
安装`xdg-utils`解决问题~

**Comment by dongweiming** [comment]
@aqiansunboy 这个错误我之前也遇到过，我改一下我fork的itchat
