### ISSUE TITLE
重启之后报错，着实不知哪出的问题

### ISSUE THREAD

**Issue by dockersky** [dongweiming/wechat-admin#42]
10.100.100.15 - - [30/Aug/2017 09:43:51] "POST /j/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/python35/lib/python3.5/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/usr/local/python35/lib/python3.5/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/python35/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/python35/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wechat-admin/views/api.py", line 88, in login
    from wechat.tasks import retrieve_data
  File "/root/wechat-admin/wechat/tasks.py", line 32, in <module>
    bot = get_bot()
  File "/root/wechat-admin/libs/wx.py", line 33, in get_bot
    here, '../static/img/qr_code.png'), console_qr=None)
  File "/root/wechat-admin/src/wxpy/wxpy/api/bot.py", line 87, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/root/wechat-admin/src/itchat/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/root/wechat-admin/src/itchat/itchat/components/login.py", line 42, in login
    uuid = push_login(self)
  File "/root/wechat-admin/src/itchat/itchat/components/login.py", line 96, in push_login
    r = core.s.get(url, headers=headers).json()
  File "/usr/local/python35/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/python35/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python35/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python35/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dongweiming** [comment]
拉验证码的时候不知道发生了什么。wechat-admin这个项目直接调用了wxpy和ItChat，你可以直接去它们项目下提issue，我没研究过网页微信的接口
