### ISSUE TITLE
群聊设置，输入关键字不能自动推送群连接。

### ISSUE THREAD

**Issue by dockersky** [dongweiming/wechat-admin#44]
运行一段时间，添加好友后自动通过，后台设置关键字推送群连接，一段时间后不好用。报错如下：
Traceback (most recent call last):
  File "/root/wechat-admin/src/itchat/itchat/components/login.py", line 275, in maintain_loop
    chatroomMsg = update_local_chatrooms(self, chatroomList)
  File "/root/wechat-admin/src/itchat/itchat/storage/__init__.py", line 12, in _contact_change
    return fn(core, *args, **kwargs)
  File "/root/wechat-admin/src/itchat/itchat/components/contact.py", line 152, in update_local_chatrooms
    'UserName', oldChatroom['ChatRoomOwner']).get('Uin', 0)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by dongweiming** [comment]
这个全程是itchat的错误，我没研究过微信API，可以问问itchat的作者 😸
