### ISSUE TITLE
获取不到联系人列表

### ISSUE THREAD

**Issue by bestfc** [dongweiming/wechat-admin#45]
没有任何错误，强制刷新也没有用

**Comment by wunifeng** [comment]
我也遇到这样的问题，获取不到联系人列表。
软硬件环境：ubuntu 14.04，python3.4，VPS 远程连接， firefox终端。第一次登录之后出现错误提示，登出并ctrl+c并且重启服务端，第二次登录之后没有任何错误提示。
第一次登录之后，错误如下：
File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/root/wechat-admin/views/settings.py", line 22, in get
    'users': [u.to_dict() for u in user.friends],
AttributeError: 'NoneType' object has no attribute 'friends'
[2017-10-03 01:50:17 +0800] [23685] [ERROR] Error handling request /j/settings/group
Traceback (most recent call last):
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/root/wechat-admin/views/settings.py", line 22, in get
    'users': [u.to_dict() for u in user.friends],
AttributeError: 'NoneType' object has no attribute 'friends'
[2017-10-03 01:54:43 +0800] [23685] [ERROR] Error handling request /j/settings/group
Traceback (most recent call last):
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/root/wechat-admin/venv/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/root/wechat-admin/views/settings.py", line 22, in get
    'users': [u.to_dict() for u in user.friends],
AttributeError: 'NoneType' object has no attribute 'friends'

**Comment by dongweiming** [comment]
目前没有人反馈这个问题.. 你可以在检查下配置和启动过程，看看有没有顺序问题？
