### ISSUE TITLE
启动Celery Beat和Worker时报AttributeError: async

### ISSUE THREAD

**Issue by tonghuaroot** [dongweiming/wechat-admin#65]
Web服务可以正常启动，当扫描完二维码，启动Celery Beat和Worker加载消息时报了个AttributeError: async错误。
详细的报错信息如下：
应该不是root权限的问题，非root用户也报这个错误。
`/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/platforms.py:793: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
Traceback (most recent call last):
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/kombu/transport/base.py", line 123, in __getattr__
    return self[key]
KeyError: 'async'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 122, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
    self._conninfo.transport.implements.async and
  File "/root/github-project/wechat-admin/venv/lib/python3.5/site-packages/kombu/transport/base.py", line 125, in __getattr__
    raise AttributeError(key)
AttributeError: async`

**Comment by tonghuaroot** [comment]
已解决：https://stackoverflow.com/questions/50444988/celery-attributeerror-async-error
