### ISSUE TITLE
执行celery报错  Signal handler <function at_start at 0x105c28d90> raised: DataError("Invalid input of type: 'AsyncResult'. Convert to a byte, string or number first.")

### ISSUE THREAD

**Issue by liyuexi** [dongweiming/wechat-admin#67]
[2019-03-25 19:42:16,562: INFO/Beat] beat: Starting... [2019-03-25 19:42:16,580: INFO/Beat] Scheduler: Sending due task wechat.tasks.send_notify (wechat.tasks.send_notify) [2019-03-25 19:42:16,727: INFO/MainProcess] Connected to redis://127.0.0.1:6379// [2019-03-25 19:42:16,734: INFO/MainProcess] mingle: searching for neighbors [2019-03-25 19:42:17,755: INFO/MainProcess] mingle: all alone [2019-03-25 19:42:17,770: ERROR/MainProcess] Signal handler <function at_start at 0x105c28d90> raised: DataError("Invalid input of type: 'AsyncResult'. Convert to a byte, string or number first.") Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/celery/utils/dispatch/signal.py", line 288, in send     response = receiver(signal=self, sender=sender, **named)   File "/Applications/XAMPP/xamppfiles/htdocs/2s/wechat_api/wechat/celery.py", line 14, in at_start     db.set(LISTENER_TASK_KEY, task_id)   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/client.py", line 1451, in set     return self.execute_command('SET', *pieces)   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/client.py", line 774, in execute_command     connection.send_command(*args)   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 620, in send_command     self.send_packed_command(self.pack_command(*args))   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 663, in pack_command     for arg in imap(self.encoder.encode, args):   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/redis/connection.py", line 125, in encode     "byte, string or number first." % typename) redis.exceptions.DataError: Invalid input of type: 'AsyncResult'. Convert to a byte, string or number first. [2019-03-25 19:42:17,773: INFO/MainProcess] celery@localhost ready. [2019-03-25 19:42:17,930: CRITICAL/MainProcess] Can't decode message body: DecodeError(TypeError("__init__() got an unexpected keyword argument 'raw'")) [type:'application/x-msgpack' encoding:'binary' headers:{'lang': 'py', 'task': 'wechat.tasks.listener', 'id': '504c6de8-c830-4c77-888f-cd3fd8fd7da6', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '504c6de8-c830-4c77-888f-cd3fd8fd7da6', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen87879@localhost'}]  body: b'\x93\x90\x80\x84\xa9callbacks\xc0\xa8errbacks\xc0\xa5chain\xc0\xa5chord\xc0' (39b) Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors     yield   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kombu/serialization.py", line 263, in loads     return decode(data)   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kombu/serialization.py", line 373, in unpack     return unpackb(s, raw=False)   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/msgpack/fallback.py", line 93, in unpackb     unpacker = Unpacker(None, **kwargs) TypeError: __init__() got an unexpected keyword argument 'raw'  During handling of the above exception, another exception occurred:

**Comment by liyuexi** [comment]
mac 10.13.4   python 3.7   Redis 4.0.11
