### ISSUE TITLE
拉取不到好友列表~

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#7]
成功登录后，界面里啥都没有，也没有联系人，后台报：

```bash
[2017-07-18 12:05:02,796: INFO/MainProcess] Connected to redis://localhost:6379//
[2017-07-18 12:05:02,813: INFO/MainProcess] mingle: searching for neighbors
[2017-07-18 12:05:03,036: INFO/Beat] beat: Starting...
[2017-07-18 12:05:03,847: INFO/MainProcess] mingle: all alone
[2017-07-18 12:05:03,881: INFO/MainProcess] celery@localhost.localdomain ready.
[2017-07-18 12:05:04,006: INFO/MainProcess] Received task: wechat.tasks.retrieve_data[09202141-7201-496e-9dcf-b11670698eab]  
[2017-07-18 12:05:04,011: INFO/MainProcess] Received task: wechat.tasks.listener[82bc9e23-0b66-4057-996c-8f3111fd0a87]  
[2017-07-18 12:05:04,021: INFO/ForkPoolWorker-3] <Bot: 大人物上篮>: joined
[2017-07-18 12:05:04,030: INFO/ForkPoolWorker-3] Task wechat.tasks.listener[82bc9e23-0b66-4057-996c-8f3111fd0a87] succeeded in 0.009817359001317527s: None
[2017-07-18 12:05:04,291: ERROR/ForkPoolWorker-2] Task wechat.tasks.retrieve_data[09202141-7201-496e-9dcf-b11670698eab] raised unexpected: AttributeError("'NoneType' object has no attribute 'mps'",)
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/wechat-admin/wechat/tasks.py", line 125, in retrieve_data
    _retrieve_data()
  File "/vagrant/wechat-admin/wechat/tasks.py", line 32, in _retrieve_data
    _update_mp(bot, update)
  File "/vagrant/wechat-admin/wechat/tasks.py", line 72, in _update_mp
    local_ids = set([m.id for m in myself.mps])
AttributeError: 'NoneType' object has no attribute 'mps'
[2017-07-18 12:05:42,885: INFO/MainProcess] Received task: wechat.tasks.update_contact[96dd7a5e-2bd0-46bb-ba3d-dbb20435fca0]  
[2017-07-18 12:05:42,902: ERROR/ForkPoolWorker-2] Task wechat.tasks.update_contact[96dd7a5e-2bd0-46bb-ba3d-dbb20435fca0] raised unexpected: AttributeError("'NoneType' object has no attribute 'friends'",)
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/wechat-admin/wechat/tasks.py", line 131, in update_contact
    _update_contact(bot, update=update)
  File "/vagrant/wechat-admin/wechat/tasks.py", line 93, in _update_contact
    local_ids = set([u.id for u in myself.friends.all()])
AttributeError: 'NoneType' object has no attribute 'friends'
```

**Comment by aqiansunboy** [comment]
好友列表里没有数据，这个问题怎么破呀，大神~

**Comment by aqiansunboy** [comment]
```bash
[2017-07-19 14:58:38 +0800] [543] [ERROR] Error handling request /j/users?gid=&page=0&q=&type=contact
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/vagrant/wechat-admin/views/api.py", line 116, in get
    users = user.friends
AttributeError: 'NoneType' object has no attribute 'friends'
```

每点一次好友列表，就输出这个错误一次。

**Comment by dongweiming** [comment]
你已经掉线了

**Comment by dongweiming** [comment]
@aqiansunboy 抱歉，这是项目的一个bug，已经修了， https://github.com/dongweiming/wechat-admin/commit/610d4f28d4e6e6d3d2f4e415cbae8c947468ca70 感谢反馈

**Comment by aqiansunboy** [comment]
@dongweiming 更新代码后，重新安装依赖，重新编译后，前端chrome控制台，出现如下错误:

```javascript

xhr.js:132 OPTIONS http://localhost:8100/j/login net::ERR_CONNECTION_REFUSED
(anonymous) @ xhr.js:132
e.exports @ required.js:3
e.exports @ whitespace.js:26
xhr.js:161 Uncaught (in promise) Error: Network Error
    at e.exports (xhr.js:161)
    at XMLHttpRequest.h.onerror (xhr.js:48)
e.exports @ xhr.js:161
h.onerror @ xhr.js:48
192.168.33.10/:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
wechat.js:46 Failed to connect to event stream
```

之前我`webpack.dev.conf.js`和`webpack.prod.conf.js`内的`API_URL`，均已改为我自己的服务器IP地址，并可以访问。

**Comment by dongweiming** [comment]
修改完，需要`npm run build`生成新的静态文件

**Comment by aqiansunboy** [comment]
@dongweiming 大神，这一步我做过了。今天重新拉取代码后重新执行依赖，重新build后又好了。但是依旧拉取不到好友列表，依旧报如下错误：

```bash
Login successfully as 大人物上篮
[2017-07-26 09:29:57 +0800] [4934] [ERROR] Error handling request /j/users?gid=&page=1&q=&type=contact
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/vagrant/wechat-admin/views/api.py", line 116, in get
    users = user.friends
AttributeError: 'NoneType' object has no attribute 'friends'
```

**Comment by dongweiming** [comment]
重新拉最新的代码么？

**Comment by dongweiming** [comment]
@aqiansunboy 这个bug我一会修一下。但是看报错，是你在登陆之后，没有正确启动celery去拉取好友等信息造成的。 你应该等任务执行一段时间再打开这个页面。
