### ISSUE TITLE
Bug还是挺多的噢，不过感谢开源，再接再厉

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#8]
再贴一条异常~

```bash
[2017-07-18 13:01:06 +0800] [28586] [ERROR] Error handling request /j/login
Traceback (most recent call last):
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 600, in __call__
    return self.app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 660, in __call__
    return app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/vagrant/wechat-admin/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/wechat-admin/views/api.py", line 83, in login
    user = get_logged_in_user(current_bot)
  File "/vagrant/wechat-admin/libs/wx.py", line 61, in get_logged_in_user
    bot.core.get_head_img(picDir=path)
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/components/contact.py", line 393, in get_head_img
    infoDict = self.storageClass.search_friends(userName=userName)
  File "/vagrant/wechat-admin/venv/src/itchat/itchat/storage/__init__.py", line 66, in search_friends
    return copy.deepcopy(self.memberList[0]) # my own account
IndexError: list index out of range
```

**Comment by dongweiming** [comment]
是你用得不对

**Comment by aqiansunboy** [comment]
我就是点了退出登录，就报这些异常噢~目前拉取不到好友列表，还没进到使用这一环节。
